### ISSUE TITLE
Havoc OS 3.3 Markw Bug Report

### ISSUE THREAD

**Issue by addy-dclxvi** [ShihabZzz/Bug_Reports#1]
Thank you for your work of maintaining Redmi 4 Prime ROMs. I flashed Havoc 3.3 several days ago and use it as daily driver. Pretty stable, but there are some bugs I found. Your Telegram channel post said that this repo purpose is for bug report, so I create a new issue here.

1. The bottom left button is treated as menu instead of recent app list
2. GPS locking is very slow
3. Android System Webview 74.x.x is outdated

And here is the list of non-bug, but aesthetic problem only

1. Phone, Messaging, Contacts, Clock, *etc* icons are not Adaptive. Instead, they look like Marshmallow icons.

Kind regards,
Addy
Markw User

**Comment by ShihabZzz** [comment]
Number 1 & 3 is not in my hand. Tell it havoc dev.
I hope next update will improve GPS locking.

aesthetic problem: Really man? It's not MIUI
