### ISSUE TITLE
LED charging off when recieving notification

### ISSUE THREAD

**Issue by Fredy2704** [ShihabZzz/Bug_Reports#11]
**Rom name+Build date**
I am usimg Havoc 3.7 build 200625

**Describe the bug**
Charging LED indicator unexpectedly off after recieving notification. I need to reconnect the usb charging cable to make the LED on again.

**Expected behavior**
LED should continue on after recieving notification.

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> [_] Goodix [*] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

> Additional information:
>
> [No] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancements

I think the problem because LED Notification and LED charging triggered at the same time.

**Comment by ShihabZzz** [comment]
It's not a bug. This is how markw LED works with AC charging + receive notification
