### ISSUE TITLE
No "back" button settings in Buttons menu

### ISSUE THREAD

**Issue by jahtor** [ShihabZzz/Bug_Reports#12]
lineage-17.1-20201019-UNOFFICIAL-markw

I see "power", " home", "menu" and "volume" buttons settings, but no "back" button menu in settings.

1. Go to 'Settings'
2. Click on 'System'
3. Click on 'Buttons'
4. No 'Back' button menu

Expected behavior: Expected 'Back' button menu

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> [_] Goodix [*] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

> Additional information:
>
> [No] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancements

**Comment by ShihabZzz** [comment]
It's not an issue. LOS doesn't have customize feature for back button.
