### ISSUE TITLE
Fingerprint and Audio balance not working

### ISSUE THREAD

**Issue by hayen-losser** [ShihabZzz/Bug_Reports#13]
Havoc-OS-v3.11-20201113-markw

Issue 1 : after installing havoc os, i cant setting my fingerprint 
Issue 2 : Audio Balance left and right not working

Setting > Accessibility > Teks Screen & Audio

![Screenshot_20201210-135416](https://user-images.githubusercontent.com/63569098/101733326-425f4000-3af1-11eb-8795-85c803b266e2.jpg)

Recovery

[] TWRP [*] OrangeFox [] Other

Gapps

[_] No [*] Yes

Fingerprint

[_] Goodix [*] FPC

Used filesystems

[*] ext4 [_] f2fs

Additional information:

[No] Dirty flash

[No] Xposed

[No] Custom kernel

[No] Performance/Battery enhancements

Additional context Add any other context about the problem here.

**Comment by hayen-losser** [comment]
audio balance accessibility not working
i cant handle left right audio

**Comment by ShihabZzz** [comment]
1. Read notes/faq section for fingerprint problem

2. Did u clean flash ?
