### ISSUE TITLE
Sim 2 doesn't work

### ISSUE THREAD

**Issue by AlmstHppSndwch** [ShihabZzz/Bug_Reports#14]
**LOS 18.1+08/01/2021**

**Describe the bug**
Sim 2 doesn't work

**To Reproduce**
1. Insert Sim
2. Doesn't work

**Expected behavior**
Insert Sim. It's working.

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> Have no idea

> Additional information:
>
> [No] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancement

**Comment by ShihabZzz** [comment]
Using Dual SIM & working fine here... Provide more information with logs
