### ISSUE TITLE
Loud speaker can't be disabled during a Call

### ISSUE THREAD

**Issue by pharaone** [ShihabZzz/Bug_Reports#15]
lineage-18.1-20210211-UNOFFICIAL-markw

**Describe the bug**
While making a call, the call automatically starts with the loud speaker activated and there is no way do use the internal speaker, pressing the loud speaker button won't do anything.

**To Reproduce**
1. Go to Dialer/WhatsApp
2. Make a call
3. Try to disable the loud speaker
4. See error: it can't be disabled and your stuck with the loudspeaker

**Expected behavior**
The call should start with the internal speaker and you should be able to activate or disable it without any problem.
**Screenshots**
![photo_2021-02-12_07-18-28](https://user-images.githubusercontent.com/17162630/107736506-87c30800-6d02-11eb-97bf-63174d822804.jpg)

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> [_] Goodix [*] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

> Additional information:
>
> [No] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancements

**Comment by faridaskerov** [comment]
I have Same issue .

**Comment by NouFox26** [comment]
> lineage-18.1-20210211-UNOFFICIAL-markw
> 
> **Describe the bug**
> While making a call, the call automatically starts with the loud speaker activated and there is no way do use the internal speaker, pressing the loud speaker button won't do anything.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to Dialer/WhatsApp
> 2. Make a call
> 3. Try to disable the loud speaker
> 4. See error: it can't be disabled and your stuck with the loudspeaker
> 
> **Expected behavior**
> The call should start with the internal speaker and you should be able to activate or disable it without any problem.
> **Screenshots**
> ![photo_2021-02-12_07-18-28](https://user-images.githubusercontent.com/17162630/107736506-87c30800-6d02-11eb-97bf-63174d822804.jpg)
> 
> **Recovery**
> 
> > [*] TWRP [_] OrangeFox [_] Other
> 
> **Gapps**
> 
> > [_] No [*] Yes
> 
> **Fingerprint**
> 
> > [_] Goodix [*] FPC
> 
> **Used filesystems**
> 
> > [*] ext4 [_] f2fs
> 
> > Additional information:
> > [No] Dirty flash
> > [No] Xposed
> > [No] Custom kernel
> > [No] Performance/Battery enhancements

I have the same issue. For whatsapp and dialer all sound route to loudspeaker even you not selecting it.

**Comment by ShihabZzz** [comment]
Fixed with latest release https://github.com/ShihabZzz/Releases/releases/tag/119.0

**Comment by pharaone** [comment]
Just updated, everything works fine. Thanks @ShihabZzz !
