### ISSUE TITLE
During using loudspeaker opposite side hear echoes of own voice

### ISSUE THREAD

**Issue by faridaskerov** [ShihabZzz/Bug_Reports#16]
**LineageOS 18.1  28/01/2021**
Currently i have this build. But the issue is exist in previous builds as well .

**Describe the bug**
When you start using loudspeaker during phone call, opposite side start to hear own voice . But using internal speaker echo disappears. 

**To Reproduce**
1. Make a phone call
2. Change voice output to loudspeaker
3. Ask opposite side to talk
4. Let him/her confirm if heard echo

**Expected behavior**
Opposite side should not hear own voice.

**Screenshots**

**Logs**
No logs

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> [*] Goodix [_] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

> Additional information:
>
> [No] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> Performance/Battery enhancements
FDE.AI 

**Additional context**

**Comment by ShihabZzz** [comment]
1. Without proper log i don't accept any issue...
2. I will not accept any bug with third party enhancements

**Comment by pharaone** [comment]
I have the same problem, and I don't have any third party enhancements.

**Comment by ShihabZzz** [comment]
> I have the same problem, and I don't have any third party enhancements.

Just writing here will not solve anything, unless u guys can provide some useful log

**Comment by pharaone** [comment]
How can I get the log? I'm sorry but I don't know how to do it
