### ISSUE TITLE
Slow Wifi 20 Mhz only

### ISSUE THREAD

**Issue by aer0nix** [ShihabZzz/Bug_Reports#17]
**Rom name+Build date**
lineage-18.1-20210307-UNOFFICIAL-markw

**Describe the bug**
Wifi use only 20 Mhz, so I got slow speed ~35 Mbps instead 70+ 

**To Reproduce**
1. Enable on router force 40 Mhz for 2.4 Ghz network
2. Connect to this Wifi
3. Do iperf3 simple test

**Expected behavior**
On router web page you can see that device will use only 20 Mhz.

**Recovery**

> [*] TWRP

**Gapps**

> [*] No 

**Fingerprint**

> [*] Goodix 

**Additional information**

Default clean install.

**Comment by ShihabZzz** [comment]
* Attach proper logcat file along with dmseg log, unless issue will be close soon.

**Comment by aer0nix** [comment]
Sadly, I already switched to another firmware. Do you can't test it with your device?

**Comment by aer0nix** [comment]
@ShihabZzz , you are miss enabling WIFI bonding mode in `/vendor/firmware/wlan/prima/WCNSS_qcom_cfg.ini`:

```
...
#Channel Bonding
gChannelBondingMode24GHz=1  <--- this is missed
gChannelBondingMode5GHz=1
...
```
This problem appear all your releases.

**Comment by ShihabZzz** [comment]
> @ShihabZzz , you are miss enabling WIFI bonding mode in `/vendor/firmware/wlan/prima/WCNSS_qcom_cfg.ini`:
> 
> ```
> ...
> #Channel Bonding
> gChannelBondingMode24GHz=1  <--- this is missed
> gChannelBondingMode5GHz=1
> ...
> ```
> 
> This problem appear all your releases.

Does it solve your slow Wi-Fi after added this line ? I removed it intentionally though

**Comment by aer0nix** [comment]
Yep.

**Comment by aer0nix** [comment]
Are you kidding? Why you removed that?

```
$ iperf3 -c 192.168.0.94
Connecting to host 192.168.0.5, port 5201
[  4] local 192.168.0.3 port 2271 connected to 192.168.0.5 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  7.75 MBytes  65.0 Mbits/sec
[  4]   1.00-2.00   sec  8.38 MBytes  70.3 Mbits/sec
[  4]   2.00-3.00   sec  10.4 MBytes  87.0 Mbits/sec
[  4]   3.00-4.00   sec  10.9 MBytes  91.2 Mbits/sec
[  4]   4.00-5.00   sec  10.4 MBytes  87.1 Mbits/sec
[  4]   5.00-6.00   sec  10.8 MBytes  90.2 Mbits/sec
[  4]   6.00-7.00   sec  10.5 MBytes  88.1 Mbits/sec
[  4]   7.00-8.00   sec  10.9 MBytes  91.2 Mbits/sec
[  4]   8.00-9.00   sec  10.4 MBytes  87.0 Mbits/sec
[  4]   9.00-10.00  sec  10.9 MBytes  91.2 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec   101 MBytes  84.8 Mbits/sec                  sender
[  4]   0.00-10.00  sec   101 MBytes  84.6 Mbits/sec                  receiver
```

**Comment by ShihabZzz** [comment]
Ok...will revert my changes.
