### ISSUE TITLE
Bootloop after encryption

### ISSUE THREAD

**Issue by aer0nix** [ShihabZzz/Bug_Reports#19]
**Rom name+Build date**
crDroidAndroid-11.0-20210403
also tested on:
lineage-18.1-20210330-UNOFFICIAL-markw
lineage-18.1-20210307-UNOFFICIAL-markw

**Describe the bug**
Bootloop after encryption

**To Reproduce**
1. Set password/PIN
2. Insert charger
3. Start encryption
3. Device can't boot

**Expected behavior**
After show password entering screen it fall to reboot again. 

**Screenshots**
None

**Logs** (not to be missed)
https://paste.ubuntu.com/p/Hw9Y6XYJgJ/

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [*] No [ ] Yes

**Fingerprint**

> [*] Goodix [ ] FPC

**Used filesystems**

> [*] ext4 [_] f2fs
I dont know. Default as is.

> Additional information:
>
> [No] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancements

**Additional context**
Any password is incorrent in TWRP /data mounting.

**Comment by ShihabZzz** [comment]
Please mention TWRP version u are using

**Comment by aer0nix** [comment]
treble 3.2.3-0-markw

**Comment by ShihabZzz** [comment]
> treble 3.2.3-0-markw

Use my mentioned TWRP from notes section. Please keep me updated

**Comment by aer0nix** [comment]
Solved.
