### ISSUE TITLE
No audio when record video from whatsapp

### ISSUE THREAD

**Issue by kapoldes** [ShihabZzz/Bug_Reports#2]
**Rom name**
Havoc-OS 3.3 - OFFICIAL

**Describe the bug**
No Audio when record video from Whatsapp, 

**To Reproduce**
1. open wahtsapp
2. record video to sent or to be a whatsapp status
**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> [_] Goodix [*] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

> Additional information:
>
> Clean flash
> [No] Custom kernel
> [No] Performance/Battery enhancements

**Additional context**

**Comment by ShihabZzz** [comment]
Give me log
