### ISSUE TITLE
[crDroid] Weird circle

### ISSUE THREAD

**Issue by aer0nix** [ShihabZzz/Bug_Reports#20]
How to disable this weird circle on left-bottom angle? He's appear when device rotated and hide keyboard or something important.

![photo_2021-04-24_01-13-39](https://user-images.githubusercontent.com/68964266/115934897-c7446800-a49a-11eb-8534-b2c2bb50e330.jpg)

**Comment by aer0nix** [comment]
Also, on crDroid debug mode enabled by default and without authorisation. Please, fix it.

**Comment by ShihabZzz** [comment]
> How to disable this weird circle on left-bottom angle? He's appear when device rotated and hide keyboard or something important.
> 
> ![photo_2021-04-24_01-13-39](https://user-images.githubusercontent.com/68964266/115934897-c7446800-a49a-11eb-8534-b2c2bb50e330.jpg)

Try to know Android 11 features & stuffs

**Comment by ShihabZzz** [comment]
> Also, on crDroid debug mode enabled by default and without authorisation. Please, fix it.

There's nothing to fix it. Why would i enable such things without authorization?
