### ISSUE TITLE
No ringtone in bluetooth headset

### ISSUE THREAD

**Issue by semka95** [ShihabZzz/Bug_Reports#24]
**Rom name+Build date**
Havoc OS 3.12 2020.12.21

**Describe the bug**
When bluetooth headset connected ringtone doesn't play in headset or phone itself.

**To Reproduce**
1. Connect any bluetooth headset (tried two different)
2. Set ring mode
3. Call on this phone
4. There's no ringtone play in headset or phone

**Expected behavior**
Ringtone should play in bluetooth headset and phone.

**Recovery**

[x] TWRP [_] OrangeFox [_] Other

**Gapps**

[x] No [x] Yes (I have two same phones with same firmware, but one with gapps)

**Fingerprint**

[*] Goodix [] FPC

**Used filesystems**

[] ext4 [*] f2fs

> Additional information:
>
> No Dirty flash
>
> One with xposed, another without
>
>No Custom kernel
>
> No Performance/Battery enhancements

**Additional context**
The thing is, if I would set vibrate mode, phone will vibrate and ringtone will play in bluetooth headset, I think it works as intended.
I also tried two phone apps (native and from google), same behavior.
And I also noticed, when I dismissed phone call, the ringtone played for fraction of a second.

**Comment by ShihabZzz** [comment]
Havoc OS 3.12 2020.12.21 discontinued

**Comment by semka95** [comment]
So, this problem is not present on crDroid 6.23, or I have to check it? @ShihabZzz
