### ISSUE TITLE
Wallpaper bug. PixelExperience ROM for markw

### ISSUE THREAD

**Issue by quiropractico** [ShihabZzz/Bug_Reports#3]
**Rom name**
PixelExperience_Plus_markw-10.0-20200329-0602-UNOFFICIAL

**Describe the bug**
When you choose an image for lock screen and a different one for starting screen, they will appear different in the upper section but when you lock the phone and look the locking screen it's the same as the starting screen. The one you select for Starting screen is the one which will appear on both sites.

**To Reproduce**
Go to **Settings - Screen - Advance - Styles and wallpapers - Wallpaper** and select two different images for both displays.

**Expected behavior**
I expected to have two different images, one for _Starting screen_ and another for _Lock screen_.

**Recovery**
TWRP 3.3.1-13

**Gapps**
> [*] No [_] Yes

**Additional information:**
I did a clean flash.

Thanks for keep doing this ROM for our markw :D

**Comment by ShihabZzz** [comment]
This is PixelExperince source bug. I can't do do anything

**Comment by quiropractico** [comment]
And how it is possible if I havve another phones with PixelExperience ROM without that problem?

thanks.

**Comment by ShihabZzz** [comment]
> And how it is possible if I have another phones with PixelExperience ROM without that problem?
> 
> thanks.

Is it markw? If it's not markw then it's end here. 
Further more u can give me logcat during this bug. 

Remember u have to catch log during setting up the wallpaper

**Comment by quiropractico** [comment]
> > And how it is possible if I have another phones with PixelExperience ROM without that problem?
> > thanks.
> 
> Is it markw? If it's not markw then it's end here.
> Further more u can give me logcat during this bug.
> 
> Remember u have to catch log during setting up the wallpaper

You are right, the others are not markw. Thanks for all.

Have a nice day!
