### ISSUE TITLE
Smart Charging doesn't work

### ISSUE THREAD

**Issue by Blelle** [ShihabZzz/Bug_Reports#5]
**Rom name**
Havoc-OS-v3.5-20200524

**Describe the bug**
When the smart charging is enabled it doesn't work, this setting stop the charging at a certain percentage (in my case at 80%) but in this ROM he goes over 80%.

**To Reproduce**
1. Go to 'Settings-> Battery -> Smart Charging'

**Expected behavior**
When i set a smart charging of 80% the phone stop to charge at 80%.

**Logs**
This logcat is from 78% to 81%

[logcat_05-25-2020_11-05-00.txt](https://github.com/ShihabZzz/Bug_Reports/files/4676323/logcat_05-25-2020_11-05-00.txt)

**Recovery*

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> [*] Goodix [] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

> Additional information:
>
> [Yes] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancements

**Additional context**

**Comment by ShihabZzz** [comment]
I hope it's fixed now

https://github.com/ShihabZzz/android_device_xiaomi_markw/commit/455244a6372a23749675ca514120aa670b8c36f9

**Comment by ShihabZzz** [comment]
wait for next update
