### ISSUE TITLE
Sound crackling while Incoming call

### ISSUE THREAD

**Issue by BlackHiruno** [ShihabZzz/Bug_Reports#9]
**Rom name+Build date**
Havoc 3.6 Wed Jun 17 10:24:46 UTC 2020

**Describe the bug**
Sound crackling while incoming call like screenshot (see screenshoot)

**To Reproduce**
1. Go to 'Home Screen' make sure your screen on
2. Make a call to your phone with other phone (Phone Call only)
3. Wait 4-5s and listen sound crackling will appear when incoming call (will appear only if you receive call like screenshot)

**Expected behavior**
Sound loud and clearly

**Screenshots**
![Incoming call](https://user-images.githubusercontent.com/43288879/86382518-00b3a900-bcb8-11ea-944b-345292e107c7.jpg)

**Logs**
Logcat from Logcat Extreme App
https://del.dog/lirfysamem

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes

**Fingerprint**

> [_] Goodix [*] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

> Additional information:
> TWRP 3.3.1-14
> [No] Dirty flash
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancements

**Additional context**
This bug not appear if you in fullscreen while incoming call

I dont know how to decribe this bug in right way. English is not my main language.

**Comment by ShihabZzz** [comment]
Please Update to latest 21 jun Havoc update
If it's possible try with Clean flash & let me know what happens

**Comment by BlackHiruno** [comment]
Ok... I will update it and give a report for this issue...

**Comment by BlackHiruno** [comment]
Im sorry for late reviewing...
This issue is fully clear in latest version Havoc 3.7
Thank you for excellent work brother

Now, i think this issue can be closed...
